name: Build ROS packages

on:
  push:

jobs:
  build-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: compas_rrc_driver
          target-ros2-distro: jazzy
